//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinabook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class QLMuonTra
    {
        public int MaMuonTra { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaSach { get; set; }
        [Display(Name = "Ngày Mượn")]
        public Nullable<System.DateTime> NgayMuon { get; set; }
        [Display(Name = "Ngày Trả")]
        public Nullable<System.DateTime> NgayTra { get; set; }
        [Display(Name = "Trạng Thái")]
        public string TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
